export * from './interfaces/call.interface'
export * from './interfaces/if.interface'
export * from './interfaces/print.interface'
export * from './interfaces/proc.interface'
export * from './interfaces/variable.interfaces'
export * from './interfaces/while.interface'
